# Default values for kafka-lagcheck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/kafka-lagcheck
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 32Mi
  requests:
    memory: 16Mi
env:
  WHITELISTED_TOPICS: ""
  BURROW_URL: ""
  MAX_LAG_TOLERANCE: ""
  ERR_LAG_TOLERANCE: ""
eksCluster: false
