# Values used for the deployed application.
replicaCount: 1
service:
  name: kafka-lagcheck
env:
  WHITELISTED_TOPICS: "SmartLogicConcepts,NativeCmsPublicationEvents,NativeCmsMetadataPublicationEvents"
  BURROW_URL: "http://burrow:8080"
  ERR_LAG_TOLERANCE: 35
  MAX_LAG_TOLERANCE: 1000
